[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[memory_usage]
format = "[RAM ${ram_pct}]($style) "
disabled = false
threshold = -1
style = "bold green"

[nodejs]
format = 'nvm [ $version](bold green) '
